### PR TITLE
Native Essentia

### LINKED ISSUE #19232: Arcane Crafting Terminal does not allow using CTRL+ to craft missing items
### Your GTNH Discord Username

Yeet

### Your Pack Version

2.7.1

### Your Server

Private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Expected the CTRL+ click to work in the ACT like in AE2 terminals to order missing craftable items

### The Reality

In the ACT you can't use CTRL+ to order craftable items for a recipe. Moreover, absent but craftable items when viewing a recipe in NEI with the ACT open are not highlighted in blue

### Your Proposal

The ACT should follow the behaviour of standard AE2 terminals

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #19917: Thaumcraft AE essentia storage in fluid tanks
### Your GTNH Discord Username

_No response_

### Your Pack Version

2.7.3

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Trying to smelt Aqua essentia and store it to AE essentia storage cell. 

### The Reality

Aqua essentia not storing in 4k Essentia storage cell and stores in empty low voltage fluid tank through AE non-filtered fluid storage bus as Aqua Super Critical Fluid by 128mb per essentia

Image

Can be stored in TFFT and other fluid tanks too, and other essentia.
Happened to other people too:
https://discord.com/channels/181078474394566657/234936569360809996/1252904114623615006
https://discord.com/channels/181078474394566657/181078474394566657/1280458590607511624

### Your Proposal

Uhh, fix storing of essentia in fluid tanks

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #20193: Arcane crafting terminal weird behaviour with large amount of items
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.7.4

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Arcane terminal will show large amounts of items correctly, as other terminals.

### The Reality

Weird arcane terminal behaviour with large amounts of items - flickering, negative amounts:
https://youtu.be/3mIxbXEgxS8

### Your Proposal

Fix this cursed terminal.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #22966: Thaumic Energistics configuration bug
### Your GTNH Discord Username

weyin

### Your Pack Version

2.8.3

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

The Thaumic Energistics config has the "ExtraCells Blacklist" parameter, which allows you to disable the ability to record gaseous essence on liquid cells.

### The Reality

However, this parameter does not work and the gaseous essence is still recorded in the cells.

### Your Proposal

I can assume that the parameter applies only to portable cells, but I would like it to apply to all others.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #23110: Essentia Terminal should have ability to dump all essentia containers with single click
### Your GTNH Discord Username

dfkls

### Your Pack Version

LATEST

### Your Proposal

Have a button to transfer all jars and other essentia containers from player's inventory to essentia network with single click. 

### Your Goal

This button greatly saves time when you need to clean up inventory from jars and when you are transferring a lot of jars into digital storage.  

### Your Vision

"Dump All" must have feature for modpack overall quality of life.

### How I see the implementation:
Have a button to the right of terminal input/output slots (red square on picture.) Since it overlaps the label, the label should be resized.
Image
 On click button would iterate though player inventory and check if it is possible to insert jar to the terminal, if so, inserts it.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [x] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [x] I believe this feature would make the pack better.

### LINKED ISSUE #23260: Arcane Crafting Terminal and Essentia Terminal cant craft items or essentia (last one being a blocker)
### Your GTNH Discord Username

xkuyax

### Your Pack Version

Daily - ThaumicEnergistics-1.7.18-GTNH.jar

### Your Server

Self hosted

### Java Version

Java 25

### Type of Server

Vanilla Forge

### Your Actions

Trying to request items/essentia does not work with the arcane crafting terminal and essentia terminal

### Crash Report

```
[10:58:50] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchMethodError: 'void appeng.container.implementations.ContainerCraftAmount.setItemToCraft(appeng.api.storage.data.IAEItemStack)'
        at Launch//thaumicenergistics.common.container.ContainerEssentiaTerminal.onClientRequestAutoCraft(ContainerEssentiaTerminal.java:157) ~[ContainerEssentiaTerminal.class:?]
        at Launch//thaumicenergistics.common.network.packet.server.Packet_S_EssentiaCellTerminal.execute(Packet_S_EssentiaCellTerminal.java:183) ~[Packet_S_EssentiaCellTerminal.class:?]
        at Launch//thaumicenergistics.common.network.WrapperPacket.execute(WrapperPacket.java:36) ~[WrapperPacket.class:?]
        at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:18) ~[HandlerServer.class:?]
        at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:14) ~[HandlerServer.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
        at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[10:58:50] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel thaumicenergistics
java.lang.NoSuchMethodError: 'void appeng.container.implementations.ContainerCraftAmount.setItemToCraft(appeng.api.storage.data.IAEItemStack)'
        at Launch//thaumicenergistics.common.container.ContainerEssentiaTerminal.onClientRequestAutoCraft(ContainerEssentiaTerminal.java:157) ~[ContainerEssentiaTerminal.class:?]
        at Launch//thaumicenergistics.common.network.packet.server.Packet_S_EssentiaCellTerminal.execute(Packet_S_EssentiaCellTerminal.java:183) ~[Packet_S_EssentiaCellTerminal.class:?]
        at Launch//thaumicenergistics.common.network.WrapperPacket.execute(WrapperPacket.java:36) ~[WrapperPacket.class:?]
        at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:18) ~[HandlerServer.class:?]
        at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:14) ~[HandlerServer.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[minecraft_server.1.7.10.jar:?]
        at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[minecraft_server.1.7.10.jar:?]
        at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

Arcane terminal:
```
[11:02:09] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel thaumicenergistics
java.lang.NoSuchMethodError: 'void appeng.container.implementations.ContainerCraftAmount.setItemToCraft(appeng.api.storage.data.IAEItemStack)'
        at Launch//thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.onClientRequestAutoCraft(ContainerPartArcaneCraftingTerminal.java:980) ~[ContainerPartArcaneCraftingTerminal.class:?]
        at Launch//thaumicenergistics.common.network.packet.server.Packet_S_ArcaneCraftingTerminal.execute(Packet_S_ArcaneCraftingTerminal.java:299) ~[Packet_S_ArcaneCraftingTerminal.class:?]
        at Launch//thaumicenergistics.common.network.WrapperPacket.execute(WrapperPacket.java:36) ~[WrapperPacket.class:?]
        at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:18) ~[HandlerServer.class:?]
        at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:14) ~[HandlerServer.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
```

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

### LINKED ISSUE #23444: Arcane terminal autocraft crash
### Your GTNH Discord Username

tiketika

### Your Pack Version

daily 340

### Your Server

private server + SP

### Java Version

Java 25

### Type of Server

None

### Your Actions

Trying to request a autocraft recipe from an arcane terminal results in a crash.

### Crash Report

java.lang.NoSuchMethodError: 'void appeng.container.implementations.ContainerCraftAmount.setItemToCraft(appeng.api.storage.data.IAEItemStack)'
at Launch//thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.onClientRequestAutoCraft(ContainerPartArcaneCraftingTerminal.java:980) ~[ContainerPartArcaneCraftingTerminal.class:?]
at Launch//thaumicenergistics.common.network.packet.server.Packet_S_ArcaneCraftingTerminal.execute(Packet_S_ArcaneCraftingTerminal.java:299) ~[Packet_S_ArcaneCraftingTerminal.class:?]
at Launch//thaumicenergistics.common.network.WrapperPacket.execute(WrapperPacket.java:36) ~[WrapperPacket.class:?]
at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:18) ~[HandlerServer.class:?]
at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:14) ~[HandlerServer.class:?]
at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [minecraft_server.1.7.10.jar:?]
at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
java.lang.NoSuchMethodError: 'void appeng.container.implementations.ContainerCraftAmount.setItemToCraft(appeng.api.storage.data.IAEItemStack)'
at Launch//thaumicenergistics.common.container.ContainerPartArcaneCraftingTerminal.onClientRequestAutoCraft(ContainerPartArcaneCraftingTerminal.java:980) ~[ContainerPartArcaneCraftingTerminal.class:?]
at Launch//thaumicenergistics.common.network.packet.server.Packet_S_ArcaneCraftingTerminal.execute(Packet_S_ArcaneCraftingTerminal.java:299) ~[Packet_S_ArcaneCraftingTerminal.class:?]
at Launch//thaumicenergistics.common.network.WrapperPacket.execute(WrapperPacket.java:36) ~[WrapperPacket.class:?]
at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:18) ~[HandlerServer.class:?]
at Launch//thaumicenergistics.common.network.HandlerServer.onMessage(HandlerServer.java:14) ~[HandlerServer.class:?]
at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
at Launch//cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
at Launch//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[minecraft_server.1.7.10.jar:?]
at Launch//io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[minecraft_server.1.7.10.jar:?]
at Launch//cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
at Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
at Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by Kogepan229**
Use AE2's StackType API to natively handle Essentia and remove Essentia hacks using fluids and fake items.
Essentia Terminal and Essentia Level Emitter are deprecated and merged into the regular ones

In addition, rewrite most of the code, inheriting the code from AE2 and significantly reducing the amount of code.

~~Backward compatibility for save data will be maintained.~~
Encoded patterns for Essentia will need to be re-encoded.
Postea is required for automatic conversion, but since there are only a few, it is better to have them manually encode it.

depends on https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/958

closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19232
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19917
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20193
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/22966
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23110
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23260
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23444

### CODE REVIEW

**Comment by lc-1337** [comment]
image

its depricated? if no, then need fix texture

**Comment by lc-1337** [comment]
image

File: src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java [hunk 1]
```diff
@@ -120,12 +138,20 @@ private void addContentsToCellDescription(final HandlerItemEssentiaCell cellHand
...
-                .collect(Collectors.toList());
+
+        List<String> list = new ArrayList<>();
+        for (AEEssentiaStack stack : cellHandler.getPartitionList().getItems()) {
+            if (stack == null) continue;
+            Aspect aspect = stack.getAspect();
+            list.add(String.format("  %s%s", aspect.getChatcolor(), stack.getDisplayName(player)));
+        }
+        return list;
+        // return cellHandler.getPartitionList().getItems().iterator().filter(Objects::nonNull)
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java]: huh

File: src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java [hunk 2]
```diff
@@ -136,16 +162,16 @@ private List<String> addPartitionsToCellDescription(final HandlerItemEssentiaCel
...
 
         // Ensure we have a cell inventory handler
-        if (!(handler instanceof HandlerItemEssentiaCell)) {
+        if (!(handler instanceof EssentiaCellInventoryHandler cellHandler)) {
             return;
         }
 
         // Cast to cell inventory handler
-        HandlerItemEssentiaCell cellHandler = (HandlerItemEssentiaCell) handler;
+        // HandlerItemEssentiaCell cellHandler = (HandlerItemEssentiaCell) handler;
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java]: //

File: src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java [hunk 3]
```diff
@@ -211,22 +237,51 @@ public double cellIdleDrain(final ItemStack itemStack, @SuppressWarnings("rawtyp
...
+                || !(essentiaCell.getItem() instanceof ItemEssentiaCell)) {
             return null;
         }
 
         // Is the type creative?
         if (essentiaCell.getItemDamage() == EnumEssentiaStorageTypes.Type_Creative.index) {
             // Return a creative handler.
-            return new HandlerItemEssentiaCellCreative(essentiaCell, saveProvider);
+            return new EssentiaCellInventoryHandler(new CreativeCellInventory<>(essentiaCell));
+            // return new HandlerItemEssentiaCellCreative(essentiaCell, saveProvider);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java]: //

File: src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java [hunk 4]
```diff
@@ -439,4 +491,77 @@ public void registerIcons(final IIconRegister iconRegister) {
...
+    }
+
+    @Override
+    public int getBytes(ItemStack cellItem) {
+        return (int) Math.min(this.getBytesLong(cellItem), Integer.MAX_VALUE);
+    }
+
+    @Override
+    public int BytePerType(ItemStack cellItem) {
+        return 0;
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java]: 0?

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java [hunk 5]
```diff
@@ -1,152 +1,272 @@
...
+            RedstoneMode redstoneMode = EnumCache.AE_REDSTONE_MODES[data.getInteger(NBT_KEY_REDSTONE_MODE)];
+            this.getConfigManager().putSetting(Settings.REDSTONE_CONTROLLED, redstoneMode);
+        }
+
+        // Read filters
+        for (int index = 0; index < MAX_FILTER_SIZE; index++) {
+            if (data.hasKey(NBT_KEY_FILTER_NUMBER + index)) {
+                Aspect aspect = Aspect.aspects.get(data.getString(NBT_KEY_FILTER_NUMBER + index));
+                if (aspect != null) {
+                    IAEStackInventory config = this.getAEInventoryByName(StorageName.NONE);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java]: StorageName.CONFIG

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java [hunk 6]
```diff
@@ -253,7 +362,7 @@ public void renderInventory(final IPartRenderHelper helper, final RenderBlocks r
         helper.renderInventoryBox(renderer);
 
         // Face overlay
-        helper.setInvColor(ThEPartBase.INVENTORY_OVERLAY_COLOR);
+        helper.setInvColor(AEColor.Black.blackVariant);
         ts.setBrightness(0xF000F0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java]: mn

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java [hunk 7]
```diff
@@ -263,7 +372,42 @@ public void renderInventory(final IPartRenderHelper helper, final RenderBlocks r
...
+
+        helper.setTexture(busColorTexture, busColorTexture, sideTexture, sideTexture, busColorTexture, busColorTexture);
+
+        // Render the box
+        helper.renderBlock(x, y, z, renderer);
+
+        // Are we active?
+        if (this.isActive()) {
+            // Set the brightness
+            Tessellator.instance.setBrightness(0xD000D0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java]: mn

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java [hunk 8]
```diff
@@ -322,7 +466,7 @@ public void renderStatic(final int x, final int y, final int z, final IPartRende
         ts.setColorOpaque_I(this.getHost().getColor().blackVariant);
 
         if (this.isActive()) {
-            Tessellator.instance.setBrightness(ThEPartBase.ACTIVE_FACE_BRIGHTNESS);
+            Tessellator.instance.setBrightness(0xD000D0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaExportBus.java]: mn

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaImportBus.java [hunk 9]
```diff
@@ -135,6 +192,36 @@ public IIcon getBreakingTexture() {
...
+
+        IIcon sideTexture = BlockTextureManager.BUS_COLOR.getTextures()[2];
+
+        helper.setTexture(busColorTexture, busColorTexture, sideTexture, sideTexture, busColorTexture, busColorTexture);
+
+        // Rend the box
+        helper.renderInventoryBox(renderer);
+
+        // Set the brightness
+        Tessellator.instance.setBrightness(0xD000D0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaImportBus.java]: mn

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaImportBus.java [hunk 10]
```diff
@@ -185,7 +272,42 @@ public void renderInventory(final IPartRenderHelper helper, final RenderBlocks r
...
+
+        helper.setTexture(busColorTexture, busColorTexture, sideTexture, sideTexture, busColorTexture, busColorTexture);
+
+        // Render the box
+        helper.renderBlock(x, y, z, renderer);
+
+        // Are we active?
+        if (this.isActive()) {
+            // Set the brightness
+            Tessellator.instance.setBrightness(0xD000D0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaImportBus.java]: mn

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaImportBus.java [hunk 11]
```diff
@@ -210,11 +332,11 @@ public void renderStatic(final int x, final int y, final int z, final IPartRende
         if (this.getHost().getColor() != AEColor.Transparent) {
             ts.setColorOpaque_I(this.getHost().getColor().blackVariant);
         } else {
-            ts.setColorOpaque_I(ThEPartBase.INVENTORY_OVERLAY_COLOR);
+            ts.setColorOpaque_I(AEColor.Black.blackVariant);
         }
 
         if (this.isActive()) {
-            Tessellator.instance.setBrightness(ThEPartBase.ACTIVE_FACE_BRIGHTNESS);
+            Tessellator.instance.setBrightness(0xD000D0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaImportBus.java]: mn

File: src/main/java/thaumicenergistics/common/parts/PartEssentiaStorageBus.java [hunk 12]
```diff
@@ -1,415 +1,113 @@
...
-    @Override
-    public void getDrops(final List<ItemStack> drops, final boolean wrenched) {
-        // Get the upgrade card
-        ItemStack slotStack = this.upgradeInventory.getStackInSlot(0);
-
-        // Is it not null?
-        if ((slotStack != null) && (slotStack.stackSize > 0)) {
-            // Add to the drops
-            drops.add(slotStack);
+        IAEStackInventory config = this.getAEInventoryByName(StorageName.NONE);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartEssentiaStorageBus.java]: StorageName.CONFIG

File: src/main/java/thaumicenergistics/common/parts/PartVisInterface.java [hunk 13]
```diff
@@ -567,6 +559,72 @@ public boolean readFromStream(final ByteBuf data) throws IOException {
...
+
+        IIcon sideTexture = BlockTextureManager.BUS_COLOR.getTextures()[2];
+
+        helper.setTexture(busColorTexture, busColorTexture, sideTexture, sideTexture, busColorTexture, busColorTexture);
+
+        // Rend the box
+        helper.renderInventoryBox(renderer);
+
+        // Set the brightness
+        Tessellator.instance.setBrightness(0xD000D0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/parts/PartVisInterface.java]: mn

File: src/main/java/thaumicenergistics/common/tiles/abstraction/TileEVCBase.java [hunk 14]
```diff
@@ -266,10 +269,13 @@ public final void onNBTLoad(final NBTTagCompound data) {
     @TileEvent(TileEventType.WORLD_NBT_WRITE)
     public final void onNBTSave(final NBTTagCompound data) {
         // Save storage
-        if (this.hasStoredEssentia()) {
+        if (this.storedEssentia != null) {
             // Save stack
             NBTTagCompound stack = new NBTTagCompound();
-            this.storedEssentia.writeToNBT(stack);
+            // this.storedEssentia.writeToNBT(stack);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/tiles/abstraction/TileEVCBase.java]: //

File: src/main/java/thaumicenergistics/common/tiles/TileEssentiaVibrationChamber.java [hunk 15]
```diff
@@ -308,28 +313,30 @@ private void updateListeners() {
...
         // Calculate how much to be stored
         int addedAmount = Math.min(amount, TileEVCBase.MAX_ESSENTIA_STORED - storedAmount);
 
-        if ((addedAmount > 0) && (mode == Actionable.MODULATE)) {
+        if (addedAmount > 0 && mode == Actionable.MODULATE) {
             // Create the stack if needed
             if (storedAspect == null) {
-                this.storedEssentia = new AspectStack(aspect, 0);
+                this.storedEssentia = new ObjectIntMutablePair<>(aspect, addedAmount);
+                // this.storedEssentia = new AspectStack(aspect, 0);
```
Comment (lc-1337) [inline src/main/java/thaumicenergistics/common/tiles/TileEssentiaVibrationChamber.java]: //

**Comment by lc-1337** [comment]
image

File: src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java (hunk 4 above)
Comment (Kogepan229) [reply src/main/java/thaumicenergistics/common/items/ItemEssentiaCell.java]: Essentia Cells have a byte count based on the amount, but it doesn't seem to be based on the type, so I kept that.
Added comment for clarification.

File: src/main/java/thaumicenergistics/common/blocks/BlockEssentiaCellWorkbench.java [hunk 16]
```diff
@@ -58,10 +59,15 @@ public BlockEssentiaCellWorkbench() {
      * @return
      */
     @Override
-    protected boolean onBlockActivated(final World world, final int x, final int y, final int z,
+    protected boolean onBlockActivated(final World world, final int x, final int y, final int z, final int side,
```
[the remark this answers is not in the document]
Comment (Kogepan229) [reply src/main/java/thaumicenergistics/common/blocks/BlockEssentiaCellWorkbench.java]: cells inside will disappear, so mark it as deprecated and leave it.

File: src/main/java/thaumicenergistics/common/ThEGuiHandler.java [hunk 17]
```diff
@@ -246,40 +136,11 @@ public static void launchGui(final int ID, final EntityPlayer player, final Worl
...
-     * @param z
-     */
-    public static void launchGui(final ThEPartBase part, final EntityPlayer player, final World world, final int x,
+    public static void launchGui(final AEBasePart part, final EntityPlayer player, final World world, final int x,
             final int y, final int z) {
         // Ensure the player is allowed to open the gui
-        if (part.isPartUseableByPlayer(player)) {
-            player.openGui(ThaumicEnergistics.INSTANCE, part.getSide().ordinal(), world, x, y, z);
-        }
+        // TODO: permission check
```
[the remark this answers is not in the document]
Comment (Kogepan229) [reply src/main/java/thaumicenergistics/common/ThEGuiHandler.java]: All permission checks required were in the AE2 GUI, so they are not necessary here.
this TODO comment is removed

**Comment by Kogepan229** [comment]
fixed now
image

**Review by lc-1337 — APPROVED** [review]
